stages:
   - test

riscv_compliance_cv32:
   stage: test
   script:
      - echo $METRICS_CI_SERVICE
      - curl -H 'Private-Token:'$METRICS_CI_SERVICE
             -H 'Content-Type:application/json' 
             -d '{"projectId":"openHW-cv32", "regressionName":"riscv_compliance_cv32", 
             "branch":"'$CI_COMMIT_REF_NAME'"}' 
             -X POST 'https://imperas.metrics.ca/api/jobs/v1/runRegression'

  
