stages:
  - test
  - deploy

testALU:
  stage: test
  script:
    - make build
    - vsim-10.5c alu_tb_optimized +UVM_TESTNAME=alu_test -do "run -a"

pages:
  stage: deploy
  script:
    - mkdocs build
    - lftp -e "mirror -R site . ; quit;" -u $FTP_USER,$FTP_PASSWORD $FTP_HOST
  artifacts:
    paths:
      - site


