stages:
  - test
  - deploy

testALU:
  stage: test
  script:
    - make build
    - make alu
    - vcover report alu.ucdb
    - vcover report -html alu.ucdb
  artifacts:
    paths:
      - covhtmlreport

testFIFO:
  stage: test
  script:
    - make build
    - make fifo
    - vcover report fifo.ucdb
    - vcover report -html fifo.ucdb
  artifacts:
    paths:
      - covhtmlreport

testScoreboard:
  stage: test
  script:
    - make build
    - make scoreboard
    - vcover report scoreboard.ucdb
    - vcover report -html scoreboard.ucdb
  artifacts:
    paths:
      - covhtmlreport

pages:
  stage: deploy
  dependencies:
    - testALU
  script:
    - mkdir public
    - mkdocs build -d public
    - mv covhtmlreport/ public/
    - lftp -e "mirror -R public . ; quit;" -u $FTP_USER,$FTP_PASSWORD $FTP_HOST
  artifacts:
    paths:
      - site


