stages:
  - deploy

publishToFTP:
  stage: deploy
  script:
    - lftp -e "mirror -R site . ; quit;" -u $FTP_USER,$FTP_PASSWORD $FTP_HOST

pages:
  stage: deploy
  script:
    - mkdocs build
  artifacts:
    paths:
      - site


