stages:
  - test
  - deploy

test_alu:
  stage: test
  script:
    - make build
    - make alu
    - vcover report alu.ucdb
    - vcover report -html alu.ucdb
  artifacts:
    paths:
      - covhtmlreport

test_fifo:
  stage: test
  script:
    - make build
    - make fifo
    - vcover report fifo.ucdb
    - vcover report -html fifo.ucdb
  artifacts:
    paths:
      - covhtmlreport

test_scoreboard:
  stage: test
  script:
    - make build
    - make scoreboard
    - vcover report scoreboard.ucdb
    - vcover report -html scoreboard.ucdb
  artifacts:
    paths:
      - covhtmlreport

test_mem_arbiter:
  stage: test
  script:
    - make build
    - make mem_arbiter
    - vcover report mem_arbiter.ucdb
    - vcover report -html mem_arbiter.ucdb
  artifacts:
    paths:
      - covhtmlreport

pages:
  stage: deploy
  dependencies:
    - test_alu
    - test_fifo
    - test_scoreboard
    - test_mem_arbiter
    - test_mem_arbiter
  script:
    - mkdir public
    - mkdocs build -d public
    - mv covhtmlreport/ public/
    - lftp -e "mirror -R public . ; quit;" -u $FTP_USER,$FTP_PASSWORD $FTP_HOST
  artifacts:
    paths:
      - site


