stages:
  - test
  - deploy

testALU:
  stage: test
  script:
    - make build
    - vsim-10.5c alu_tb_optimized -c +UVM_TESTNAME=alu_test -coverage -do "coverage save -onexit alu.ucdb; run -a; exit"
    - vcover report -html alu.ucdb
  artifacts:
    paths:
      - covhtmlreport


pages:
  stage: deploy
  dependencies:
    - testALU
  script:
    - mkdocs build
    - lftp -e "mirror -R site . ; quit;" -u $FTP_USER,$FTP_PASSWORD $FTP_HOST
    - covhtmlreport/ site/
  artifacts:
    paths:
      - site


