language: cpp
matrix:
  include:
  # works on Precise and Trusty
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
compiler:
  - gcc
before_install:
  - eval "${MATRIX_EVAL}"
  - ci/make-tmp.sh
  - ci/install-fesvr.sh
  - ci/install-verilator.sh
  - ci/build-riscv-tests.sh
  - export VERILATOR_ROOT=$CI_PROJECT_DIR/tmp/verilator-3.918/
script:
  - make run-asm-tests-verilator verilator=$TRAVIS_BUILD_DIR/tmp/bin/verilator
