site_name: Ariane
pages:
  - Home: 'index.md'
  - Architecture: 'architecture.md'
  - Block Details: 'block_details.md'
  - Ideas: 'ideas.md'
  - Test Bench: 'tb.md'
  - Synthesis Results: 'synthesis.md'
  - Timing Diagrams: 'timing_diagrams.md'

# cosmo, readthedocs, journal, slate, material, readable, spacelab, united, bootstrap, simplex, flatly, yeti, amelia, cerulean, cyborg, mkdocs
theme: 'flatly'
extra_javascript: [js/default.js, js/wavedrom.min.js, js/ariane.js]
