site_name: Ariane
pages:
  - Home: 'index.md'
  - Architecture: 'architecture.md'
  - Block Details: 'block_details.md'
  - Ideas: 'ideas.md'
  - Test Bench: 'tb.md'
  - Synthesis Results: 'synthesis.md'
# cosmo, readthedocs, journal, slate, material, readable, spacelab, united, bootstrap, simplex, flatly, yeti, amelia, cerulean, cyborg, mkdocs
theme: 'flatly'
